os: linux

dist: bionic

language: php

php:
    - '7.4'
    - '7.3'

env:
    - SYMFONY_VERSION=5.1.*
    - SYMFONY_VERSION=5.0.*
    - SYMFONY_VERSION=4.4.*

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --no-scripts --prefer-dist
    - composer update --prefer-dist

script:
    - vendor/bin/psalm
    - vendor/bin/phpunit
    - phpdbg -qrr vendor/bin/infection --min-msi=100

